server1 ansible_host=192.168.100.10 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/server1/virtualbox/private_key
server2 ansible_host=192.168.100.11 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/server2/virtualbox/private_key
server3 ansible_host=192.168.100.12 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/server3/virtualbox/private_key

[kafka_broker_servers]
server[1:3]
